// 전체 사용자 데이터 (42명)
const allUsers = [
  {
    id: 1,
    name: "이현희",
    email: "hyunhee@mail.com",
    organization: "건국대학교",
    authority: "관리자",
  },
  {
    id: 2,
    name: "김영준",
    email: "youngjune@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 3,
    name: "박지영",
    email: "jiyoung@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 4,
    name: "곽민재",
    email: "minjae@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 5,
    name: "정수민",
    email: "sumin@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 6,
    name: "송태호",
    email: "taeho@mail.com",
    organization: "UKET",
    authority: "관리자",
  },
  {
    id: 7,
    name: "강다은",
    email: "daeun@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 8,
    name: "조민수",
    email: "minsu@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 9,
    name: "윤서진",
    email: "seojin@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 10,
    name: "임주원",
    email: "juwon@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 11,
    name: "한지우",
    email: "jiwoo@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 12,
    name: "오승환",
    email: "seunghwan@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 13,
    name: "나은성",
    email: "eunsung@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 14,
    name: "최지한",
    email: "jihan@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 15,
    name: "이승호",
    email: "seungho@mail.com",
    organization: "서울대학교",
    authority: "관리자",
  },
  {
    id: 16,
    name: "김도윤",
    email: "doyun@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 17,
    name: "박민준",
    email: "minjun@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 18,
    name: "정예준",
    email: "yejun@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 19,
    name: "장서윤",
    email: "seoyun@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 20,
    name: "황지민",
    email: "jimin@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 21,
    name: "류하은",
    email: "haeun@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 22,
    name: "안소율",
    email: "soyul@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 23,
    name: "손지훈",
    email: "jihoon@mail.com",
    organization: "건국대학교",
    authority: "관리자",
  },
  {
    id: 24,
    name: "백승민",
    email: "seungmin@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 25,
    name: "홍지원",
    email: "jiwon@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 26,
    name: "배현서",
    email: "hyunseo@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 27,
    name: "문준영",
    email: "junyoung@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 28,
    name: "노유진",
    email: "yujin@mail.com",
    organization: "UKET",
    authority: "관리자",
  },
  {
    id: 29,
    name: "양세준",
    email: "sejun@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 30,
    name: "구민석",
    email: "minseok@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 31,
    name: "조서연",
    email: "seoyeon@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 32,
    name: "권지호",
    email: "jiho@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 33,
    name: "신유나",
    email: "yuna@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 34,
    name: "전민규",
    email: "mingyu@mail.com",
    organization: "건국대학교",
    authority: "관리자",
  },
  {
    id: 35,
    name: "서지안",
    email: "jian@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 36,
    name: "남도현",
    email: "dohyun@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 37,
    name: "육지후",
    email: "jihoo@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 38,
    name: "설윤아",
    email: "yoona@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 39,
    name: "방주혁",
    email: "juhyuk@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 40,
    name: "공서율",
    email: "seoyul@mail.com",
    organization: "고려대학교",
    authority: "관리자",
  },
  {
    id: 41,
    name: "하승우",
    email: "seungwoo@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 42,
    name: "채지수",
    email: "jisoo@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 43,
    name: "임하진",
    email: "hajin@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 44,
    name: "강민호",
    email: "minho@mail.com",
    organization: "건국대학교",
    authority: "관리자",
  },
  {
    id: 45,
    name: "이서아",
    email: "seoa@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 46,
    name: "김도현",
    email: "dohyeon@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 47,
    name: "박준서",
    email: "junseo@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 48,
    name: "정유진",
    email: "youjin@mail.com",
    organization: "UKET",
    authority: "관리자",
  },
  {
    id: 49,
    name: "윤지원",
    email: "jiwon2@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 50,
    name: "조승현",
    email: "seunghyun@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 51,
    name: "한서연",
    email: "seoyeon2@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 52,
    name: "신동현",
    email: "donghyun@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 53,
    name: "장민서",
    email: "minseo@mail.com",
    organization: "고려대학교",
    authority: "관리자",
  },
  {
    id: 54,
    name: "황준호",
    email: "junho@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 55,
    name: "류지현",
    email: "jihyun@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 56,
    name: "안현우",
    email: "hyunwoo@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 57,
    name: "손예린",
    email: "yerin@mail.com",
    organization: "연세대학교",
    authority: "관리자",
  },
  {
    id: 58,
    name: "백지훈",
    email: "jihoon2@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 59,
    name: "홍서현",
    email: "seohyun@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 60,
    name: "배민준",
    email: "minjun2@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
  {
    id: 61,
    name: "문서윤",
    email: "seoyun2@mail.com",
    organization: "UKET",
    authority: "관리자",
  },
  {
    id: 62,
    name: "노지민",
    email: "jimin2@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 63,
    name: "양하은",
    email: "haeun2@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 64,
    name: "구윤서",
    email: "yoonseo@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 65,
    name: "조민재",
    email: "minjae2@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 66,
    name: "권수빈",
    email: "subin@mail.com",
    organization: "건국대학교",
    authority: "관리자",
  },
  {
    id: 67,
    name: "신지우",
    email: "jiwoo2@mail.com",
    organization: "UKET",
    authority: "멤버",
  },
  {
    id: 68,
    name: "전승우",
    email: "seungwoo2@mail.com",
    organization: "서울대학교",
    authority: "멤버",
  },
  {
    id: 69,
    name: "서도현",
    email: "dohyun2@mail.com",
    organization: "연세대학교",
    authority: "멤버",
  },
  {
    id: 70,
    name: "남지안",
    email: "jian2@mail.com",
    organization: "UKET",
    authority: "관리자",
  },
  {
    id: 71,
    name: "육서율",
    email: "seoyul2@mail.com",
    organization: "고려대학교",
    authority: "멤버",
  },
  {
    id: 72,
    name: "설주혁",
    email: "juhyuk2@mail.com",
    organization: "건국대학교",
    authority: "멤버",
  },
];


// 관리자 삭제 함수
export function deleteAdmin(adminId: number) {
  const index = allUsers.findIndex((user) => user.id === adminId);
  if (index !== -1) {
    allUsers.splice(index, 1);
    return true;
  }
  return false;
}

// 관리자 추가 함수
export function addAdmin() {
  const newId = Math.max(...allUsers.map((user) => user.id)) + 1;
  const newAdmin = {
    id: newId,
    name: "",
    email: "",
    organization: "",
    authority: "멤버",
  };
  allUsers.push(newAdmin);
  return newAdmin;
}

// 페이지네이션 함수
export function getAdmin(page = 1, size = 10) {
  const startIndex = (page - 1) * size;
  const endIndex = startIndex + size;
  const paginatedUsers = allUsers.slice(startIndex, endIndex);

  return {
    content: paginatedUsers,
    pageNumber: page,
    pageSize: size,
    first: page === 0,
    last: endIndex >= allUsers.length,
    totalElements: allUsers.length,
    totalPages: Math.ceil(allUsers.length / size),
    empty: paginatedUsers.length === 0,
  };
}
